#!/usr/bin/expect -f
set timeout -1
spawn scp fix_nginx.sh root@193.53.127.116:/root/
expect {
    "password:" {
        send "m3h9W0pI8D1Z5Wq\r"
        exp_continue
    }
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    eof
}

spawn ssh root@193.53.127.116 "chmod +x /root/fix_nginx.sh && /root/fix_nginx.sh"
expect {
    "password:" {
        send "m3h9W0pI8D1Z5Wq\r"
        exp_continue
    }
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    eof
}
